from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 350)
        self.OK = QtWidgets.QDialogButtonBox(Dialog)
        self.OK.setGeometry(QtCore.QRect(40, 300, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.OK.setFont(font)
        self.OK.setOrientation(QtCore.Qt.Horizontal)
        self.OK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.OK.setCenterButtons(True)
        self.OK.setObjectName("OK")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(180, 40, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.comboBox_6 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout.addWidget(self.comboBox_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.comboBox_7 = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout.addWidget(self.comboBox_7)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(10, 40, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.widget1.setFont(font)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.retranslateUi(Dialog)
        self.OK.accepted.connect(Dialog.accept) # type: ignore
        self.OK.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Сентябрь"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Октябрь"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Ноябрь"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "Декабрь"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "Январь"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "Февраль"))
        self.comboBox_4.setItemText(6, _translate("Dialog", "Март"))
        self.comboBox_4.setItemText(7, _translate("Dialog", "Апрель"))
        self.comboBox_4.setItemText(8, _translate("Dialog", "Май"))
        self.comboBox_4.setItemText(9, _translate("Dialog", "Июнь"))
        self.comboBox.setItemText(0, _translate("Dialog", "1"))
        self.comboBox.setItemText(1, _translate("Dialog", "2"))
        self.comboBox.setItemText(2, _translate("Dialog", "3"))
        self.comboBox.setItemText(3, _translate("Dialog", "4"))
        self.comboBox.setItemText(4, _translate("Dialog", "5"))
        self.comboBox.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "ДМ"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "ИнфИС11к"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "ИнфИС12к"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "ИнфЮр11К"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "ИнфЮр21К"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "ИнфЮр22К"))
        self.comboBox_5.setItemText(6, _translate("Dialog", "ИнфЮр23К"))
        self.comboBox_5.setItemText(7, _translate("Dialog", "ИТИС21к"))
        self.comboBox_5.setItemText(8, _translate("Dialog", "МатИС11к"))
        self.comboBox_5.setItemText(9, _translate("Dialog", "УПр"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "ИС21к"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "ИС11к"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "ИС12к"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "ЮР11к"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "ЮР21к"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "ЮР22к"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "ЮР23к"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "0"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "Лекция"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Практика"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Урок"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "№Н/Д"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_3.setItemText(8, _translate("Dialog", "9"))
        self.comboBox_3.setItemText(9, _translate("Dialog", "10"))
        self.comboBox_3.setItemText(10, _translate("Dialog", "11"))
        self.comboBox_3.setItemText(11, _translate("Dialog", "12"))
        self.comboBox_3.setItemText(12, _translate("Dialog", "13"))
        self.comboBox_3.setItemText(13, _translate("Dialog", "14"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "Я"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "Другой"))
        self.label.setText(_translate("Dialog", "Месяц"))
        self.label_2.setText(_translate("Dialog", "№ Пары"))
        self.label_3.setText(_translate("Dialog", "Предмет"))
        self.label_9.setText(_translate("Dialog", "Группа"))
        self.label_5.setText(_translate("Dialog", "Вид занятия"))
        self.label_6.setText(_translate("Dialog", "Неделя"))
        self.label_4.setText(_translate("Dialog", "Кто"))
